apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: webapp
  name: webapp-controller
spec:
  replicas: 2
  selector:
    name: webapp
  template:
    metadata:
      labels:
        name: webapp
    spec:
      containers:
      - image: ch0ppy35/zero-to-hero:k8s
        name: webapp
        ports:
        - containerPort: 3000
          name: http-server